import faker from "faker";
const randomNumber = faker.random.number(2);

export const tempItems = [
         {
           itemId: 1,
           owner: faker.random.number(10),
           title: faker.commerce.productName(),
           description: faker.lorem.paragraph(),
           brand: faker.company.companyName(),
           model: `${faker.lorem.words(1)}${faker.random.number()}`,
           dailyPrice: faker.commerce.price(),
           weeklyPrice: faker.finance.amount(),
           label: faker.commerce.department(),
           available: faker.random.boolean(),
           renter: randomNumber === 1 ? faker.random.number(500) : false,
           image: faker.random.image()
         },
         {
           itemId: 2,
           owner: faker.random.number(10),
           title: faker.commerce.productName(),
           description: faker.lorem.paragraph(),
           brand: faker.company.companyName(),
           model: `${faker.lorem.words(1)}${faker.random.number()}`,
           dailyPrice: faker.commerce.price(),
           weeklyPrice: faker.finance.amount(),
           label: faker.commerce.department(),
           available: faker.random.boolean(),
           renter: randomNumber === 1 ? faker.random.number(500) : false,
           image: faker.random.image()
         },
         {
           itemId: 3,
           owner: faker.random.number(10),
           title: faker.commerce.productName(),
           description: faker.lorem.paragraph(),
           brand: faker.company.companyName(),
           model: `${faker.lorem.words(1)}${faker.random.number()}`,
           dailyPrice: faker.commerce.price(),
           weeklyPrice: faker.finance.amount(),
           label: faker.commerce.department(),
           available: faker.random.boolean(),
           renter: randomNumber === 1 ? faker.random.number(500) : false,
           image: faker.random.image()
         },
         {
           itemId: 4,
           owner: faker.random.number(10),
           title: faker.commerce.productName,
           description: faker.lorem.paragraph(),
           brand: faker.company.companyName(),
           model: `${faker.lorem.words(1)}${faker.random.number()}`,
           dailyPrice: faker.commerce.price(),
           weeklyPrice: faker.finance.amount(),
           label: faker.commerce.department(),
           available: faker.random.boolean(),
           renter: randomNumber === 1 ? faker.random.number(500) : false,
           image: faker.random.image()
         },
         {
           itemId: 5,
           owner: faker.random.number(10),
           title: faker.commerce.productName(),
           description: faker.lorem.paragraph(),
           brand: faker.company.companyName(),
           model: `${faker.lorem.words(1)}${faker.random.number()}`,
           dailyPrice: faker.commerce.price(),
           weeklyPrice: faker.finance.amount(),
           label: faker.commerce.department(),
           available: faker.random.boolean(),
           renter: randomNumber === 1 ? faker.random.number(500) : false,
           image: faker.random.image()
         },
         {
           itemId: 6,
           owner: faker.random.number(10),
           title: faker.commerce.productName(),
           description: faker.lorem.paragraph(),
           brand: faker.company.companyName(),
           model: `${faker.lorem.words(1)}${faker.random.number()}`,
           dailyPrice: faker.commerce.price(),
           weeklyPrice: faker.finance.amount(),
           label: faker.commerce.department(),
           available: faker.random.boolean(),
           renter: randomNumber === 1 ? faker.random.number(500) : false,
           image: faker.random.image()
         },
         {
           itemId: 7,
           owner: faker.random.number(10),
           title: faker.commerce.productName(),
           description: faker.lorem.paragraph(),
           brand: faker.company.companyName(),
           model: `${faker.lorem.words(1)}${faker.random.number()}`,
           dailyPrice: faker.commerce.price(),
           weeklyPrice: faker.finance.amount(),
           label: faker.commerce.department(),
           available: faker.random.boolean(),
           renter: randomNumber === 1 ? faker.random.number(500) : false,
           image: faker.random.image()
         },
         {
           itemId: 8,
           owner: faker.random.number(10),
           title: faker.commerce.productName(),
           description: faker.lorem.paragraph(),
           brand: faker.company.companyName(),
           model: `${faker.lorem.words(1)}${faker.random.number()}`,
           dailyPrice: faker.commerce.price(),
           weeklyPrice: faker.finance.amount(),
           label: faker.commerce.department(),
           available: faker.random.boolean(),
           renter: randomNumber === 1 ? faker.random.number(500) : false,
           image: faker.random.image()
         },
         {
           itemId: 9,
           owner: faker.random.number(10),
           title: faker.commerce.productName(),
           description: faker.lorem.paragraph(),
           brand: faker.company.companyName(),
           model: `${faker.lorem.words(1)}${faker.random.number()}`,
           dailyPrice: faker.commerce.price(),
           weeklyPrice: faker.finance.amount(),
           label: faker.commerce.department(),
           available: faker.random.boolean(),
           renter: randomNumber === 1 ? faker.random.number(500) : false,
           image: faker.random.image()
         },
         {
           itemId: 10,
           owner: faker.random.number(10),
           title: faker.commerce.productName(),
           description: faker.lorem.paragraph(),
           brand: faker.company.companyName(),
           model: `${faker.lorem.words(1)}${faker.random.number()}`,
           dailyPrice: faker.commerce.price(),
           weeklyPrice: faker.finance.amount(),
           label: faker.commerce.department(),
           available: faker.random.boolean(),
           renter: randomNumber === 1 ? faker.random.number(500) : false,
           image: faker.random.image()
         },
         {
           itemId: 11,
           owner: faker.random.number(10),
           title: faker.commerce.productName(),
           description: faker.lorem.paragraph(),
           brand: faker.company.companyName(),
           model: `${faker.lorem.words(1)}${faker.random.number()}`,
           dailyPrice: faker.commerce.price(),
           weeklyPrice: faker.finance.amount(),
           label: faker.commerce.department(),
           available: faker.random.boolean(),
           renter: randomNumber === 1 ? faker.random.number(500) : false,
           image: faker.random.image()
         },
         {
           itemId: 12,
           owner: faker.random.number(10),
           title: faker.commerce.productName(),
           description: faker.lorem.paragraph(),
           brand: faker.company.companyName(),
           model: `${faker.lorem.words(1)}${faker.random.number()}`,
           dailyPrice: faker.commerce.price(),
           weeklyPrice: faker.finance.amount(),
           label: faker.commerce.department(),
           available: faker.random.boolean(),
           renter: randomNumber === 1 ? faker.random.number(500) : false,
           image: faker.random.image()
         },
         {
           itemId: 13,
           owner: faker.random.number(10),
           title: faker.commerce.productName(),
           description: faker.lorem.paragraph(),
           brand: faker.company.companyName(),
           model: `${faker.lorem.words(1)}${faker.random.number()}`,
           dailyPrice: faker.commerce.price(),
           weeklyPrice: faker.finance.amount(),
           label: faker.commerce.department(),
           available: faker.random.boolean(),
           renter: randomNumber === 1 ? faker.random.number(500) : false,
           image: faker.random.image()
         },
         {
           itemId: 14,
           owner: faker.random.number(10),
           title: faker.commerce.productName(),
           description: faker.lorem.paragraph(),
           brand: faker.company.companyName(),
           model: `${faker.lorem.words(1)}${faker.random.number()}`,
           dailyPrice: faker.commerce.price(),
           weeklyPrice: faker.finance.amount(),
           label: faker.commerce.department(),
           available: faker.random.boolean(),
           renter: randomNumber === 1 ? faker.random.number(500) : false,
           image: faker.random.image()
         },
         {
           itemId: 15,
           owner: faker.random.number(10),
           title: faker.commerce.productName(),
           description: faker.lorem.paragraph(),
           brand: faker.company.companyName(),
           model: `${faker.lorem.words(1)}${faker.random.number()}`,
           dailyPrice: faker.commerce.price(),
           weeklyPrice: faker.finance.amount(),
           label: faker.commerce.department(),
           available: faker.random.boolean(),
           renter: randomNumber === 1 ? faker.random.number(500) : false,
           image: faker.random.image()
         }
       ];

export const tempUsers = [
  {
    userId: 1,
    username: faker.internet.userName(),
    password: faker.internet.password(),
    firstName: faker.name.firstName(),
    lastName: faker.name.lastName(),
    email: faker.internet.email(),
    phone: faker.phone.phoneNumber()
  },
  {
    userId: 2,
    username: faker.internet.userName(),
    password: faker.internet.password(),
    firstName: faker.name.firstName(),
    lastName: faker.name.lastName(),
    email: faker.internet.email(),
    phone: faker.phone.phoneNumber()
  },
  {
    userId: 3,
    username: faker.internet.userName(),
    password: faker.internet.password(),
    firstName: faker.name.firstName(),
    lastName: faker.name.lastName(),
    email: faker.internet.email(),
    phone: faker.phone.phoneNumber()
  },
  {
    userId: 4,
    username: faker.internet.userName(),
    password: faker.internet.password(),
    firstName: faker.name.firstName(),
    lastName: faker.name.lastName(),
    email: faker.internet.email(),
    phone: faker.phone.phoneNumber()
  },
  {
    userId: 5,
    username: faker.internet.userName(),
    password: faker.internet.password(),
    firstName: faker.name.firstName(),
    lastName: faker.name.lastName(),
    email: faker.internet.email(),
    phone: faker.phone.phoneNumber()
  },
  {
    userId: 6,
    username: faker.internet.userName(),
    password: faker.internet.password(),
    firstName: faker.name.firstName(),
    lastName: faker.name.lastName(),
    email: faker.internet.email(),
    phone: faker.phone.phoneNumber()
  },
  {
    userId: 7,
    username: faker.internet.userName(),
    password: faker.internet.password(),
    firstName: faker.name.firstName(),
    lastName: faker.name.lastName(),
    email: faker.internet.email(),
    phone: faker.phone.phoneNumber()
  },
  {
    userId: 8,
    username: faker.internet.userName(),
    password: faker.internet.password(),
    firstName: faker.name.firstName(),
    lastName: faker.name.lastName(),
    email: faker.internet.email(),
    phone: faker.phone.phoneNumber()
  },
  {
    userId: 9,
    username: faker.internet.userName(),
    password: faker.internet.password(),
    firstName: faker.name.firstName(),
    lastName: faker.name.lastName(),
    email: faker.internet.email(),
    phone: faker.phone.phoneNumber()
  },
  {
    userId: 10,
    username: faker.internet.userName(),
    password: faker.internet.password(),
    firstName: faker.name.firstName(),
    lastName: faker.name.lastName(),
    email: faker.internet.email(),
    phone: faker.phone.phoneNumber()
  }
];
